project:
  type: book

lang: es

book:
  title: "IC-datasets-docencia"
  author: "Instituto de Cálculo"
  date: last-modified
  chapters:
    - index.qmd
    - 01_regresion.qmd
    - 02_regresion_multiple.qmd
    - 03_test_hipotesis.qmd
    - 04_visualizacion.qmd
    - references.qmd
  appendices:
    - otros-datasets.qmd
  page-navigation: true
  favicon: cover.png
  repo-url: https://daniellaparada.github.io/IC-datasets-docencia/
  downloads: [pdf, epub]

crossref:
  appendix-title: "Apéndice"
  appendix-delim: ":"

bibliography: references.bib

format:
  html:
    theme: cosmo
    page-layout: full

execute:
  freeze: auto

prefer-html: true

code-fold: true
code-overflow: wrap
code-summary: "Ver código"

editor: visual

