# Anexo: otros *datasets* {.unnumbered}

Ver si va (ejemplo dummy)

| *Dataset*                             | Temas |
|---------------------------------------|-------|
| [`bateria.csv`](#sec-bateria)         | XXX   |
| [`nombres-arg.csv`](#sec-nombres-arg) | XXX   |



## Descripción, variables y fuente

```{r, message=FALSE, warning=FALSE, echo=FALSE}
require(devtools)
require(knitr)
devtools::install_github("daniellaparada/datosIC")
library(datosIC)
```

------------------------------------------------------------------------

### `bateria.csv`{#sec-bateria}

-   **Descripción**: Datos del historial de capacidad de carga de una batería de Li-Ion L19M4PC2 con capacidad de fábrica de 80.000 mWh en una Notebook LENOVO 81YT con 505 ciclos de carga.

-   **Variables**:

    -   `desde`: fecha de inicio del período, en el formato año-mes-día.
    -   `hasta`: fecha de finalización del período, en el formato año-mes-día.
    -   `carga`: carga máxima alcanzada (mWh) durante el período.

-   **Fuente**: Reporte generado a partir de la instrucción `powercfg /batteryreport` en Windows 11. 

Disponible en la librería `datosIC` bajo el nombre de `bateria`.

```{r, message=FALSE, warning=FALSE}
data(bateria)
knitr::kable(bateria[1:10,], caption = "Dataset 'bateria' disponible en la librería 'datosIC'.")
```


------------------------------------------------------------------------

### `nombres-arg.csv`{#sec-nombres-arg}

-   **Descripción**: Datos de.

-   **Variables**:

    -   `XXX`:

-   **Fuente**: XXX

------------------------------------------------------------------------