{
  "hash": "dc1d0cb5f03167c12f952793340260f7",
  "result": {
    "markdown": "Presentamos un ejemplo para test de hipótesis a partir de datos reales de clima y de flujo vehicular de la Ciudad Autónoma de Buenos Aires.\n\n![Cómo *MidJourney* imagina que se ilustra este problema bajo el *prompt*: */imagine a lively cityscape of Buenos Aires with the striking Obelisk towering in the center. Set the scene on a rainy day, a bustling street surrounding the Obelisk, showcasing a diverse array of cars and commuters. Divide the scene in two, with more cars in one side. Incorporate a rainy atmosphere creating puddles on the ground, and adding reflections of lights and cityscape in the wet pavement*.](./fuente/03_test_hipotesis/apertura.png){fig-align=\"center\"}\n\n# Test de hipótesis\n\nA continuación, se muestran algunos posibles análisis para datos de flujo vehicular en CABA incorporando, en algunos casos, variables climáticas.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls())\n# Librerías necesarias\nrequire(ggplot2)\nrequire(tidyverse)\nrequire(ggfortify)\nrequire(plotly)\nrequire(vroom)\nrequire(effsize)\nrequire(ggmap)\nrequire(leaflet)\nrequire(devtools)\noptions(scipen = 999)\n```\n:::\n\n\n\n## Exploración inicial\n\nLos datos de flujo vehicular de la Ciudad de Buenos Aires reportan, por hora, la cantidad de vehículos registrados por radares ubicados en diferentes puntos de algunas autopistas de la ciudad.\n\nEn el siguiente mapa se muestra el total de flujo vehicular para cada uno de los radares durante 2019.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# importo datos de flujo vehicular 2019\nflujo19 <-\n  vroom(\"./fuente/03_test_hipotesis/flujo-vehicular-por-radares-2019.csv\") %>%\n  group_by(disp_ubicacion) %>%\n  summarise(n = sum(cantidad),\n            lat = mean(lat),\n            long = mean(long)) %>%\n  drop_na()\n\npaleta <- colorQuantile(\"Greys\", flujo19$n, n = 6)\n\n# Mapa\nmapa19 <- flujo19 %>%\n  leaflet(options = leafletOptions(attributionControl = FALSE)) %>%\n  addProviderTiles(\"CartoDB.VoyagerLabelsUnder\",\n                   options = providerTileOptions(opacity = 0.8)) %>%\n  addCircleMarkers(\n    lng = ~ long,\n    lat = ~ lat,\n    fillOpacity = 0.9,\n    radius =  ~ 100 * n / (sum(n)),\n    weight = 1,\n    color = ~ paleta(n),\n    stroke = FALSE\n  )\nmapa19\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"leaflet html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-10e7b187b669fa6204d3\" style=\"width:1650px;height:1050px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-10e7b187b669fa6204d3\">{\"x\":{\"options\":{\"crs\":{\"crsClass\":\"L.CRS.EPSG3857\",\"code\":null,\"proj4def\":null,\"projectedBounds\":null,\"options\":{}},\"attributionControl\":false},\"calls\":[{\"method\":\"addProviderTiles\",\"args\":[\"CartoDB.VoyagerLabelsUnder\",null,null,{\"errorTileUrl\":\"\",\"noWrap\":false,\"opacity\":0.8,\"detectRetina\":false}]},{\"method\":\"addCircleMarkers\",\"args\":[[-34.6513498298016,-34.6506100000003,-34.6841100000013,-34.6435747938655,-34.6394,-34.6407599999999,-34.6389800000019,-34.6345799999993,-34.6699000000004,-34.6346199999985,-34.6326000000004,-34.6604400000039,-34.6546499999987,-34.6532903687257,-34.5633600000001,-34.5604400000009,-34.549769999999,-34.5477799999982,-34.5462899999986,-34.5436199999989,-34.5429299999987,-34.5423000000007,-34.5373807893306],[-58.3726040639072,-58.4667699999993,-58.4826400000016,-58.3757950527496,-58.3763500000025,-58.3765100000012,-58.3769500000024,-58.377630000002,-58.4753599999997,-58.3777899999988,-58.3786100000072,-58.4712400000047,-58.4690100000007,-58.4681496023173,-58.4152900000026,-58.4190799999992,-58.4360199999959,-58.4384800000011,-58.4422400000023,-58.4464000000006,-58.4490100000027,-58.4486899999994,-58.4594156940672],[5.61484162640272,0.404578104745365,7.42576571574751,5.05054601028104,2.96808882164934,3.18642920574249,2.87506893817651,3.02195984756824,0.440443165731613,2.05875893715488,6.48178754700179,5.01431361745705,6.23106481003714,1.23919786578319,5.02663671461061,5.60893398538263,3.3530918590574,2.39376062432709,6.2808640559242,3.4753720142411,6.14929572126065,4.74291014591991,10.9562906657976],null,null,{\"interactive\":true,\"className\":\"\",\"stroke\":false,\"color\":[\"#636363\",\"#F7F7F7\",\"#252525\",\"#969696\",\"#D9D9D9\",\"#BDBDBD\",\"#D9D9D9\",\"#D9D9D9\",\"#F7F7F7\",\"#F7F7F7\",\"#252525\",\"#969696\",\"#636363\",\"#F7F7F7\",\"#969696\",\"#636363\",\"#BDBDBD\",\"#D9D9D9\",\"#252525\",\"#BDBDBD\",\"#636363\",\"#969696\",\"#252525\"],\"weight\":1,\"opacity\":0.5,\"fill\":true,\"fillColor\":[\"#636363\",\"#F7F7F7\",\"#252525\",\"#969696\",\"#D9D9D9\",\"#BDBDBD\",\"#D9D9D9\",\"#D9D9D9\",\"#F7F7F7\",\"#F7F7F7\",\"#252525\",\"#969696\",\"#636363\",\"#F7F7F7\",\"#969696\",\"#636363\",\"#BDBDBD\",\"#D9D9D9\",\"#252525\",\"#BDBDBD\",\"#636363\",\"#969696\",\"#252525\"],\"fillOpacity\":0.9},null,null,null,null,null,{\"interactive\":false,\"permanent\":false,\"direction\":\"auto\",\"opacity\":1,\"offset\":[0,0],\"textsize\":\"10px\",\"textOnly\":false,\"className\":\"\",\"sticky\":true},null]}],\"limits\":{\"lat\":[-34.6841100000013,-34.5373807893306],\"lng\":[-58.4826400000016,-58.3726040639072]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n\nComo puede observarse en el mapa, el radar ubicado en la Autopista Lugones altura ESMA (RD 171), es el que mayor flujo registra para el año considerado. Los datos de 2023, que al momento de producir este documento solo se encuentran disponibles para el primer trimestre del año, exhiben una tendencia similar (a efectos creativos, se representan sobre un mapa en formato acuarelas: [conocer más acá](http://maps.stamen.com/)).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# importo datos de flujo vehicular 2023\nflujo23 <-\n  vroom(\"./fuente/03_test_hipotesis/flujo-vehicular-por-radares-2023.csv\")\n\n# La long y la lat está mal registrada\ncorregir_lat <- which(flujo23$lat > -500000)\nflujo23$lat[corregir_lat] <- flujo23$lat[corregir_lat] / 10000\nflujo23$lat[-corregir_lat] <- flujo23$lat[-corregir_lat] / 100000\n\ncorregir_long <- which(flujo23$long > -1000000)\nflujo23$long[corregir_long] <- flujo23$long[corregir_long] / 10000\nflujo23$long[-corregir_long] <- flujo23$long[-corregir_long] / 100000\n\nflujo23 <- flujo23 %>%\n  group_by(disp_ubicacion) %>%\n  summarise(n = sum(cantidad),\n            lat = mean(lat),\n            long = mean(long)) %>%\n  drop_na()\n\npaleta <- colorQuantile(\"Greys\", flujo23$n, n = 6)\n\n# Mapa\nmapa23 <- flujo23 %>%\n  leaflet(options = leafletOptions(attributionControl = FALSE)) %>%\n  addProviderTiles(\"Stamen.Watercolor\",\n                   options = providerTileOptions(opacity = 0.8)) %>%\n  addCircleMarkers(\n    lng = ~ long,\n    lat = ~ lat,\n    fillOpacity = 0.9,\n    radius =  ~ 100 * n / (sum(n)),\n    weight = 1,\n    color = ~ paleta(n),\n    stroke = FALSE\n  )\nmapa23\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"leaflet html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-755e4ebad71399af8a8a\" style=\"width:1650px;height:1050px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-755e4ebad71399af8a8a\">{\"x\":{\"options\":{\"crs\":{\"crsClass\":\"L.CRS.EPSG3857\",\"code\":null,\"proj4def\":null,\"projectedBounds\":null,\"options\":{}},\"attributionControl\":false},\"calls\":[{\"method\":\"addProviderTiles\",\"args\":[\"Stamen.Watercolor\",null,null,{\"errorTileUrl\":\"\",\"noWrap\":false,\"opacity\":0.8,\"detectRetina\":false}]},{\"method\":\"addCircleMarkers\",\"args\":[[-34.65135,-34.65061,-34.68411,-34.67917,-34.64358,-34.6394,-34.64076,-34.6699,-34.6326,-34.62277,-34.65465,-34.6532499589217,-34.65134,-34.56336,-34.56044,-34.54977,-34.54778,-34.54629,-34.54362,-34.54293,-34.5423,-34.5373800671452],[-58.372605,-58.46677,-58.48264,-58.47959,-58.37592,-58.37635,-58.37651,-58.47536,-58.37861,-58.37825,-58.46901,-58.4681525956354,-58.46643,-58.41529,-58.41908,-58.43602,-58.43848,-58.44224,-58.4464,-58.44901,-58.44869,-58.4594150590414],[4.88407974206096,0.566272793857427,6.20797985537067,6.24579542081181,2.29423363263523,2.92060923013247,3.24181213180191,8.59872073477994,5.89667335363571,0.0151042129077409,4.69805924682247,0.964436595331672,0.0552527062831408,5.15692523495964,5.7167495767321,5.78058805599998,2.59778584082868,6.62948908722711,5.38193493784619,5.47335341079029,5.20711967493197,11.4670245242529],null,null,{\"interactive\":true,\"className\":\"\",\"stroke\":false,\"color\":[\"#BDBDBD\",\"#F7F7F7\",\"#636363\",\"#252525\",\"#D9D9D9\",\"#D9D9D9\",\"#BDBDBD\",\"#252525\",\"#636363\",\"#F7F7F7\",\"#BDBDBD\",\"#F7F7F7\",\"#F7F7F7\",\"#BDBDBD\",\"#636363\",\"#636363\",\"#D9D9D9\",\"#252525\",\"#969696\",\"#969696\",\"#969696\",\"#252525\"],\"weight\":1,\"opacity\":0.5,\"fill\":true,\"fillColor\":[\"#BDBDBD\",\"#F7F7F7\",\"#636363\",\"#252525\",\"#D9D9D9\",\"#D9D9D9\",\"#BDBDBD\",\"#252525\",\"#636363\",\"#F7F7F7\",\"#BDBDBD\",\"#F7F7F7\",\"#F7F7F7\",\"#BDBDBD\",\"#636363\",\"#636363\",\"#D9D9D9\",\"#252525\",\"#969696\",\"#969696\",\"#969696\",\"#252525\"],\"fillOpacity\":0.9},null,null,null,null,null,{\"interactive\":false,\"permanent\":false,\"direction\":\"auto\",\"opacity\":1,\"offset\":[0,0],\"textsize\":\"10px\",\"textOnly\":false,\"className\":\"\",\"sticky\":true},null]}],\"limits\":{\"lat\":[-34.68411,-34.5373800671452],\"lng\":[-58.48264,-58.372605]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n\nPara lo que sigue, trabajamos con el *dataset* reducido `flujovehicular.csv` en el que se incluyen datos del flujo vehicular de los días hábiles del primer trimestre de 2019 y de 2023 para el radar RD 171 ubicado en la Autopista Lugones, altura ESMA, sentido A.\n\nEl dataset `flujo-vehicular.csv` se encuentra [acá](https://www.dropbox.com/scl/fi/4lzzhbi3avqq945wno0e2/flujo-clima.csv?rlkey=nl9m3bxm9jhfrbpjs08pcg4af&dl=0). A continuación, se muestran 10 datos de dicho conjunto.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndatos <- read_csv(\"./fuente/03_test_hipotesis/flujo-vehicular.csv\")\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\nTable: Dataset reducido, primeras 10 observaciones.\n\n|fecha |    n19|    n23|\n|:-----|------:|------:|\n|01-02 | 108550| 108794|\n|01-03 | 118754| 114959|\n|01-04 | 120250| 117394|\n|01-09 |  49684| 118142|\n|01-10 | 121533| 119916|\n|01-11 | 123864| 120939|\n|01-16 |  27560| 119623|\n|01-17 | 121897| 118654|\n|01-18 | 123497| 119748|\n|01-23 | 121223| 118691|\n:::\n:::\n\n\n\nCada observación corresponde al flujo total detectado por ese radar de un día que resultó hábil tanto en 2019 como en 2023. La elección de los años responde a lo siguiente: - los datos de 2020 y 2021 van a encontrarse influenciados por las restricciones de circulación de la pandemia de COVID-19 y la paulatina vuelta a la presencialidad, - los datos de 2022 no se encuentran disponibles para el año completo, sino para algunos meses al inicio y al fin del año.\n\nComo puede verse en el siguiente gráfico, existe una tendencia temporal que incide en el flujo vehicular del trimestre para ambos años.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-c727ee68b382ed87bae5\" style=\"width:1650px;height:1050px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-c727ee68b382ed87bae5\">{\"x\":{\"data\":[{\"x\":[108550,118754,120250,49684,121533,123864,27560,121897,123497,121223,124459,120236,130254,127283,133461,132200,127075,131823,134963,132903,134665,132751,138079,133705,131290,135200,133874,139612,null,132214,null,129146],\"y\":[108794,114959,117394,118142,119916,120939,119623,118654,119748,118691,118186,121207,127126,124436,119747,127764,120605,131878,131423,93178,95786,129345,128168,130569,130951,131701,127865,127546,133183,136693,138603,129581],\"text\":[\"fecha: 01-02\",\"fecha: 01-03\",\"fecha: 01-04\",\"fecha: 01-09\",\"fecha: 01-10\",\"fecha: 01-11\",\"fecha: 01-16\",\"fecha: 01-17\",\"fecha: 01-18\",\"fecha: 01-23\",\"fecha: 01-24\",\"fecha: 01-25\",\"fecha: 02-01\",\"fecha: 02-06\",\"fecha: 02-07\",\"fecha: 02-08\",\"fecha: 02-13\",\"fecha: 02-14\",\"fecha: 02-15\",\"fecha: 02-20\",\"fecha: 02-21\",\"fecha: 02-22\",\"fecha: 03-01\",\"fecha: 03-06\",\"fecha: 03-07\",\"fecha: 03-08\",\"fecha: 03-13\",\"fecha: 03-14\",\"fecha: 03-15\",\"fecha: 03-20\",\"fecha: 03-22\",\"fecha: 03-27\"],\"key\":[\"01-02\",\"01-03\",\"01-04\",\"01-09\",\"01-10\",\"01-11\",\"01-16\",\"01-17\",\"01-18\",\"01-23\",\"01-24\",\"01-25\",\"02-01\",\"02-06\",\"02-07\",\"02-08\",\"02-13\",\"02-14\",\"02-15\",\"02-20\",\"02-21\",\"02-22\",\"03-01\",\"03-06\",\"03-07\",\"03-08\",\"03-13\",\"03-14\",\"03-15\",\"03-20\",\"03-22\",\"03-27\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(178,34,34,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(178,34,34,1)\"}},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"_isNestedKey\":false,\"frame\":null},{\"x\":[-7000,147000],\"y\":[-7000,147000],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"dash\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":27.4807566862361,\"r\":7.30593607305936,\"b\":41.4350945857795,\"l\":60.6392694063927},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-7000,147000],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"50000\",\"100000\"],\"tickvals\":[0,50000,100000],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"50000\",\"100000\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Flujo vehicular Lugones (Esma) 2019\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-7000,147000],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"50000\",\"100000\"],\"tickvals\":[0,50000,100000],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"50000\",\"100000\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Flujo vehicular Lugones (Esma) 2023\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.88976377952756,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.689497716895}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"select\",\"attrs\":{\"60c35503c53\":{\"x\":{},\"y\":{},\"key\":{},\"type\":\"scatter\"},\"60c2db01c0c\":{\"intercept\":{},\"slope\":{}}},\"cur_data\":\"60c35503c53\",\"visdat\":{\"60c35503c53\":[\"function (y) \",\"x\"],\"60c2db01c0c\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n\nLas observaciones que se encuentran más alejadas de la recta identidad, corresponden a los días 20 y 21 de febrero de 2023, ambos feriados de carnaval, y a los días 9 y 16 de enero de 2019, ambos lunes, de posible retorno a la ciudad por recambio turístico. Removemos estas observaciones para lo que sigue.\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-22e4c3505f16b40b6714\" style=\"width:1650px;height:1050px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-22e4c3505f16b40b6714\">{\"x\":{\"data\":[{\"x\":[108550,118754,120250,121533,123864,121897,123497,121223,124459,120236,130254,127283,133461,132200,127075,131823,134963,132751,138079,133705,131290,135200,133874,139612,null,132214,null,129146],\"y\":[108794,114959,117394,119916,120939,118654,119748,118691,118186,121207,127126,124436,119747,127764,120605,131878,131423,129345,128168,130569,130951,131701,127865,127546,133183,136693,138603,129581],\"text\":[\"fecha: 01-02\",\"fecha: 01-03\",\"fecha: 01-04\",\"fecha: 01-10\",\"fecha: 01-11\",\"fecha: 01-17\",\"fecha: 01-18\",\"fecha: 01-23\",\"fecha: 01-24\",\"fecha: 01-25\",\"fecha: 02-01\",\"fecha: 02-06\",\"fecha: 02-07\",\"fecha: 02-08\",\"fecha: 02-13\",\"fecha: 02-14\",\"fecha: 02-15\",\"fecha: 02-22\",\"fecha: 03-01\",\"fecha: 03-06\",\"fecha: 03-07\",\"fecha: 03-08\",\"fecha: 03-13\",\"fecha: 03-14\",\"fecha: 03-15\",\"fecha: 03-20\",\"fecha: 03-22\",\"fecha: 03-27\"],\"key\":[\"01-02\",\"01-03\",\"01-04\",\"01-10\",\"01-11\",\"01-17\",\"01-18\",\"01-23\",\"01-24\",\"01-25\",\"02-01\",\"02-06\",\"02-07\",\"02-08\",\"02-13\",\"02-14\",\"02-15\",\"02-22\",\"03-01\",\"03-06\",\"03-07\",\"03-08\",\"03-13\",\"03-14\",\"03-15\",\"03-20\",\"03-22\",\"03-27\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(178,34,34,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(178,34,34,1)\"}},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"_isNestedKey\":false,\"frame\":null},{\"x\":[98000,142000],\"y\":[98000,142000],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"dash\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":27.4807566862361,\"r\":7.30593607305936,\"b\":41.4350945857795,\"l\":60.6392694063927},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[98000,142000],\"tickmode\":\"array\",\"ticktext\":[\"100000\",\"110000\",\"120000\",\"130000\",\"140000\"],\"tickvals\":[100000,110000,120000,130000,140000],\"categoryorder\":\"array\",\"categoryarray\":[\"100000\",\"110000\",\"120000\",\"130000\",\"140000\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Flujo vehicular Lugones (Esma) 2019\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[98000,142000],\"tickmode\":\"array\",\"ticktext\":[\"100000\",\"110000\",\"120000\",\"130000\",\"140000\"],\"tickvals\":[100000,110000,120000,130000,140000],\"categoryorder\":\"array\",\"categoryarray\":[\"100000\",\"110000\",\"120000\",\"130000\",\"140000\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Flujo vehicular Lugones (Esma) 2023\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.88976377952756,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.689497716895}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"select\",\"attrs\":{\"60c2f9e5f33\":{\"x\":{},\"y\":{},\"key\":{},\"type\":\"scatter\"},\"60c4c6b832\":{\"intercept\":{},\"slope\":{}}},\"cur_data\":\"60c2f9e5f33\",\"visdat\":{\"60c2f9e5f33\":[\"function (y) \",\"x\"],\"60c4c6b832\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n\nLos datos exhiben una estacionalidad que, naturalmente, afecta al usual supuesto de independencia: el flujo es creciente, para ambos años, a medida que transcurren los días durante el primer trimestre. Sumado a eso, el emparejamiento de los días por su simple correspondencia de fecha podría no ser comparable, salvo excepciones o hitos de cada año.\n\nPor ejemplo, la observación del 24 de enero de 2019 podría no ser comparable con la equivalente de 2023, aunque sí, quizás, con el de alguna fecha próxima a ella. Por la limitación de los datos disponibles para 2023, no es posible considerar otro tipo de agrupamientos. Sin embargo y pese a esto, el flujo vehicular registrado por ese radar parecer ser sistemáticamente menor en 2023 en relación con 2019.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-30849806380207497b3a\" style=\"width:1650px;height:1050px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-30849806380207497b3a\">{\"x\":{\"data\":[{\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28],\"y\":[108550,118754,120250,121533,123864,121897,123497,121223,124459,120236,130254,127283,133461,132200,127075,131823,134963,132751,138079,133705,131290,135200,133874,139612,142666,132214,140071,129146],\"text\":[\"dia: 01-02\",\"dia: 01-03\",\"dia: 01-04\",\"dia: 01-10\",\"dia: 01-11\",\"dia: 01-17\",\"dia: 01-18\",\"dia: 01-23\",\"dia: 01-24\",\"dia: 01-25\",\"dia: 02-01\",\"dia: 02-06\",\"dia: 02-07\",\"dia: 02-08\",\"dia: 02-13\",\"dia: 02-14\",\"dia: 02-15\",\"dia: 02-22\",\"dia: 03-01\",\"dia: 03-06\",\"dia: 03-07\",\"dia: 03-08\",\"dia: 03-13\",\"dia: 03-14\",\"dia: 03-15\",\"dia: 03-20\",\"dia: 03-22\",\"dia: 03-27\"],\"key\":[\"01-02\",\"01-03\",\"01-04\",\"01-10\",\"01-11\",\"01-17\",\"01-18\",\"01-23\",\"01-24\",\"01-25\",\"02-01\",\"02-06\",\"02-07\",\"02-08\",\"02-13\",\"02-14\",\"02-15\",\"02-22\",\"03-01\",\"03-06\",\"03-07\",\"03-08\",\"03-13\",\"03-14\",\"03-15\",\"03-20\",\"03-22\",\"03-27\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(238,18,137,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(238,18,137,1)\"}},\"hoveron\":\"points\",\"name\":\"2019\",\"legendgroup\":\"2019\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"_isNestedKey\":false,\"frame\":null},{\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28],\"y\":[108794,114959,117394,119916,120939,118654,119748,118691,118186,121207,127126,124436,119747,127764,120605,131878,131423,129345,128168,130569,130951,131701,127865,127546,133183,136693,138603,129581],\"text\":[\"dia: 01-02\",\"dia: 01-03\",\"dia: 01-04\",\"dia: 01-10\",\"dia: 01-11\",\"dia: 01-17\",\"dia: 01-18\",\"dia: 01-23\",\"dia: 01-24\",\"dia: 01-25\",\"dia: 02-01\",\"dia: 02-06\",\"dia: 02-07\",\"dia: 02-08\",\"dia: 02-13\",\"dia: 02-14\",\"dia: 02-15\",\"dia: 02-22\",\"dia: 03-01\",\"dia: 03-06\",\"dia: 03-07\",\"dia: 03-08\",\"dia: 03-13\",\"dia: 03-14\",\"dia: 03-15\",\"dia: 03-20\",\"dia: 03-22\",\"dia: 03-27\"],\"key\":[\"01-02\",\"01-03\",\"01-04\",\"01-10\",\"01-11\",\"01-17\",\"01-18\",\"01-23\",\"01-24\",\"01-25\",\"02-01\",\"02-06\",\"02-07\",\"02-08\",\"02-13\",\"02-14\",\"02-15\",\"02-22\",\"03-01\",\"03-06\",\"03-07\",\"03-08\",\"03-13\",\"03-14\",\"03-15\",\"03-20\",\"03-22\",\"03-27\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(28,134,238,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(28,134,238,1)\"}},\"hoveron\":\"points\",\"name\":\"2023\",\"legendgroup\":\"2023\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"_isNestedKey\":false,\"frame\":null}],\"layout\":{\"margin\":{\"t\":27.4807566862361,\"r\":7.30593607305936,\"b\":29.7455968688845,\"l\":60.6392694063927},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.4,28.6],\"tickmode\":\"array\",\"ticktext\":{},\"tickvals\":[],\"categoryorder\":\"array\",\"categoryarray\":{},\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Día (solo para lunes a viernes de ambos años)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[106844.2,144371.8],\"tickmode\":\"array\",\"ticktext\":[\"110000\",\"120000\",\"130000\",\"140000\"],\"tickvals\":[110000,120000,130000,140000],\"categoryorder\":\"array\",\"categoryarray\":[\"110000\",\"120000\",\"130000\",\"140000\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Flujo vehicular Lugones (Esma)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.88976377952756,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.689497716895},\"title\":{\"text\":\"Año\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"select\",\"attrs\":{\"60c5730248c\":{\"x\":{},\"y\":{},\"colour\":{},\"key\":{},\"type\":\"scatter\"}},\"cur_data\":\"60c5730248c\",\"visdat\":{\"60c5730248c\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n\n## Test para diferencia de medias (datos apareados: primer trimestre 2019 vs 2023)\n\nBajo ciertos reparos, puede ponerse a prueba la hipótesis anterior, asumiendo que algo de la estacionalidad observada puede resolverse apareando los datos. Más precisamente, un gráfico de las diferencias entre el flujo de 2019 y el de 2023 para los días considerados parece dar cuenta de tal efecto.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-43e4cea8a9ce53bcdd62\" style=\"width:1650px;height:1050px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-43e4cea8a9ce53bcdd62\">{\"x\":{\"data\":[{\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28],\"y\":[-244,3795,2856,1617,2925,3243,3749,2532,6273,-971,3128,2847,13714,4436,6470,-55,3540,3406,9911,3136,339,3499,6009,12066,9483,-4479,1468,-435],\"text\":[\"dia: 01-02\",\"dia: 01-03\",\"dia: 01-04\",\"dia: 01-10\",\"dia: 01-11\",\"dia: 01-17\",\"dia: 01-18\",\"dia: 01-23\",\"dia: 01-24\",\"dia: 01-25\",\"dia: 02-01\",\"dia: 02-06\",\"dia: 02-07\",\"dia: 02-08\",\"dia: 02-13\",\"dia: 02-14\",\"dia: 02-15\",\"dia: 02-22\",\"dia: 03-01\",\"dia: 03-06\",\"dia: 03-07\",\"dia: 03-08\",\"dia: 03-13\",\"dia: 03-14\",\"dia: 03-15\",\"dia: 03-20\",\"dia: 03-22\",\"dia: 03-27\"],\"key\":[\"01-02\",\"01-03\",\"01-04\",\"01-10\",\"01-11\",\"01-17\",\"01-18\",\"01-23\",\"01-24\",\"01-25\",\"02-01\",\"02-06\",\"02-07\",\"02-08\",\"02-13\",\"02-14\",\"02-15\",\"02-22\",\"03-01\",\"03-06\",\"03-07\",\"03-08\",\"03-13\",\"03-14\",\"03-15\",\"03-20\",\"03-22\",\"03-27\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(127,127,127,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(127,127,127,1)\"}},\"hoveron\":\"points\",\"name\":\"grey\",\"legendgroup\":\"grey\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"_isNestedKey\":false,\"frame\":null},{\"x\":[0.4,28.6],\"y\":[0,0],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,139,69,1)\",\"dash\":\"dash\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0.4,28.6],\"y\":[3723.5,3723.5],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(178,34,34,1)\",\"dash\":\"dash\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":27.4807566862361,\"r\":7.30593607305936,\"b\":29.7455968688845,\"l\":54.7945205479452},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.4,28.6],\"tickmode\":\"array\",\"ticktext\":{},\"tickvals\":[],\"categoryorder\":\"array\",\"categoryarray\":{},\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Día (solo para lunes a viernes de ambos años)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-5388.65,14623.65],\"tickmode\":\"array\",\"ticktext\":[\"-5000\",\"0\",\"5000\",\"10000\"],\"tickvals\":[-5000,0,5000,10000],\"categoryorder\":\"array\",\"categoryarray\":[\"-5000\",\"0\",\"5000\",\"10000\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Diferencia de flujo vehicular 2019 vs 2023\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.88976377952756,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.689497716895}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"select\",\"attrs\":{\"60c9207078\":{\"x\":{},\"y\":{},\"colour\":{},\"key\":{},\"type\":\"scatter\"},\"60c6b2c6f1f\":{\"yintercept\":{}},\"60c14ab7312\":{\"yintercept\":{}}},\"cur_data\":\"60c9207078\",\"visdat\":{\"60c9207078\":[\"function (y) \",\"x\"],\"60c6b2c6f1f\":[\"function (y) \",\"x\"],\"60c14ab7312\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n\nParte de la estacionalidad parece haberse corregido y la media observada para las diferencias, que debería ser cercana a 0 en caso de no haber diferencias, se observa desplazada sugiriendo un flujo promedio mayor en 2019.\n\nRealizamos un test t para muestras apareadas a nivel $1\\%$.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](03_test_hipotesis_files/figure-pdf/unnamed-chunk-11-1.pdf)\n:::\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  flujosout$n19 and flujosout$n23\nt = 4.9782, df = 27, p-value = 0.0000323\nalternative hypothesis: true mean difference is not equal to 0\n99 percent confidence interval:\n 1651.119 5795.881\nsample estimates:\nmean difference \n         3723.5 \n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCohen's d\n\nd estimate: 0.4958838 (small)\n95 percent confidence interval:\n    lower     upper \n0.2842526 0.7075150 \n```\n:::\n:::\n\n\n\nEn efecto, el $p-$valor es $0.0000323$, y a partir de esta muestra y bajo las consideraciones ya mencionadas, rechazaríamos el supuesto de igualdad de flujos medios para ambos años, durante días hábiles del primer trimestre en ese radar. El tamaño del efecto parece ser moderado.\n\n## Incorporamos datos de clima\n\nPara lo que sigue, trabajamos con el *dataset* reducido `flujoclima` de la librería `datosIC` en el que se incluyen datos del flujo vehicular del primer trimestre de 2023 para el radar RD 171 ubicado en la Autopista Lugones, altura ESMA, sentido A, junto con datos de temperatura promedio y precipitaciones. A continuación, se muestran 10 datos de dicho conjunto.\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndevtools::install_github(\"daniellaparada/datosIC\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n-- R CMD build -----------------------------------------------------------------\n* checking for file 'C:\\Users\\dpara\\AppData\\Local\\Temp\\RtmpG8z4ae\\remotes60c781d5e21\\daniellaparada-datosIC-07715ff/DESCRIPTION' ... OK\n* preparing 'datosIC':\n* checking DESCRIPTION meta-information ... OK\n* checking for LF line-endings in source and make files and shell scripts\n* checking for empty or unneeded directories\n* building 'datosIC_0.0.0.9000.tar.gz'\n\n```\n:::\n\n```{.r .cell-code}\nlibrary(datosIC)\ndatos <- flujoclima\n```\n:::\n\n\n\nUn gráfico del flujo vehicular por tipo de día y según nivel de precipitaciones, parece mostrar lo esperado: el el flujo vehicular en ese punto de la ciudad es mayor los días de semana que los fines de semana. Sin embargo, no parece haber una tendencia notable que impacte en el flujo vehicular a partir de las precipitaciones. Dicha tendencia podría ser creciente, asumiendo que los días en que se registran mayores niveles de precipitaciones más personas utilizan el auto; o bien decreciente, sugiriendo que hay menor tránsito vehicular porque las personas prefieren suspender aquellas actividades fuera de sus hogares que no sean esenciales.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nflujoclima <- datos\nggplotly(\n  ggplot(\n    data = filter(flujoclima),\n    aes(\n      x = factor(\n        dia,\n        level = c(\n          \"lunes\",\n          \"martes\",\n          \"miércoles\",\n          \"jueves\",\n          \"viernes\",\n          \"sábado\",\n          \"domingo\"\n        )\n      ),\n      y = n,\n      color = tipo_dia,\n      key = prcp\n    )\n  ) +\n    geom_point(aes(size = prcp)) +\n    labs(\n      x = \"Días de la semana\",\n      y = \"Flujo vehicular Lugones (Esma)\",\n      color = \"Tipo de día\",\n      size = \"Precipitaciones\"\n    ) +\n    scale_color_manual(values = c(\"Fin de semana\" = \"deeppink2\", \"Lunes a viernes\" = \"dodgerblue2\")) +\n    theme_classic(),\n  source = \"select\",\n  tooltip = c(\"key\")\n)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-1ad83575b0988dc9f901\" style=\"width:1650px;height:1050px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-1ad83575b0988dc9f901\">{\"x\":{\"data\":[{\"x\":[7,6,7,6,7,6,7,6,7,6,7,6,7,6,7,6,7,6,7,6,7,6,7,6,7],\"y\":[74642,94076,92560,97825,95381,93157,94484,95487,98060,105183,103598,102803,101175,104070,96004,108241,105287,113880,109826,112777,107133,125809,112527,107914,109421],\"text\":[\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp: 16.0\",\"prcp:  7.9\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  5.1\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  7.1\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  4.1\",\"prcp: 18.4\",\"prcp:  0.0\"],\"key\":[\"0\",\"0\",\"0\",\"0\",\"0\",\"16\",\"7.9\",\"0\",\"0\",\"5.1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"7.1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"4.1\",\"18.4\",\"0\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(238,18,137,1)\",\"opacity\":1,\"size\":[3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,21.4016656675335,16.1621364243217,3.77952755905512,3.77952755905512,13.7286252967989,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,15.5184378464057,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,12.7000550841254,22.6771653543307,3.77952755905512],\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(238,18,137,1)\"}},\"hoveron\":\"points\",\"name\":\"Fin de semana\",\"legendgroup\":\"Fin de semana\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"_isNestedKey\":false,\"frame\":null},{\"x\":[1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5],\"y\":[108794,114959,117394,120350,118283,118142,119916,120939,126514,122459,119623,118654,119748,121885,115121,118691,118186,121207,124058,114261,120384,125220,127126,127772,126526,124436,119747,127764,129709,129590,120605,131878,131423,129934,131541,93178,95786,129345,131524,132096,127755,130982,128168,135349,137729,130569,130951,131701,138352,141459,127865,127546,133183,139144,142102,136693,135091,138603,122690,98285,129581,131213,133103,141028,146072],\"text\":[\"prcp:  9.9\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.3\",\"prcp:  0.0\",\"prcp:  2.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp: 17.0\",\"prcp:  0.0\",\"prcp:  0.2\",\"prcp:  0.0\",\"prcp: 14.2\",\"prcp:  7.1\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  7.1\",\"prcp:  0.0\",\"prcp:  4.9\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  1.5\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  5.2\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.3\",\"prcp:  8.2\",\"prcp:  1.1\",\"prcp:  0.8\",\"prcp:  3.0\",\"prcp:  0.0\",\"prcp:  0.1\",\"prcp:  4.2\",\"prcp:  0.2\",\"prcp:  0.0\",\"prcp:  0.0\",\"prcp:  0.8\",\"prcp:  0.0\",\"prcp:  0.0\"],\"key\":[\"9.9\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0.3\",\"0\",\"2\",\"0\",\"0\",\"17\",\"0\",\"0.2\",\"0\",\"14.2\",\"7.1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"7.1\",\"0\",\"4.9\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1.5\",\"0\",\"0\",\"5.2\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0.3\",\"8.2\",\"1.1\",\"0.8\",\"3\",\"0\",\"0.1\",\"4.2\",\"0.2\",\"0\",\"0\",\"0.8\",\"0\",\"0\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(28,134,238,1)\",\"opacity\":1,\"size\":[17.6412183379415,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,6.19253819742637,3.77952755905512,10.0098942368106,3.77952755905512,3.77952755905512,21.9440117516748,3.77952755905512,5.74974249502748,3.77952755905512,20.3808536949073,15.5184378464057,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,15.5184378464057,3.77952755905512,13.5315939504026,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,9.17518337688341,3.77952755905512,3.77952755905512,13.8256919635501,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512,6.19253819742637,16.3950585685319,8.40009115201725,7.71995743099984,11.4101371945252,3.77952755905512,5.17267990067619,12.808186638481,5.74974249502748,3.77952755905512,3.77952755905512,7.71995743099984,3.77952755905512,3.77952755905512],\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(28,134,238,1)\"}},\"hoveron\":\"points\",\"name\":\"Lunes a viernes\",\"legendgroup\":\"Lunes a viernes\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"_isNestedKey\":false,\"frame\":null}],\"layout\":{\"margin\":{\"t\":27.4807566862361,\"r\":7.30593607305936,\"b\":41.4350945857795,\"l\":60.6392694063927},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.4,7.6],\"tickmode\":\"array\",\"ticktext\":[\"lunes\",\"martes\",\"miércoles\",\"jueves\",\"viernes\",\"sábado\",\"domingo\"],\"tickvals\":[1,2,3,4,5,6,7],\"categoryorder\":\"array\",\"categoryarray\":[\"lunes\",\"martes\",\"miércoles\",\"jueves\",\"viernes\",\"sábado\",\"domingo\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Días de la semana\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[71070.5,149643.5],\"tickmode\":\"array\",\"ticktext\":[\"90000\",\"110000\",\"130000\"],\"tickvals\":[90000,110000,130000],\"categoryorder\":\"array\",\"categoryarray\":[\"90000\",\"110000\",\"130000\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Flujo vehicular Lugones (Esma)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.88976377952756,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.689497716895},\"title\":{\"text\":\"Tipo de día<br />Precipitaciones\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"select\",\"attrs\":{\"60c2c04487e\":{\"x\":{},\"y\":{},\"colour\":{},\"key\":{},\"size\":{},\"type\":\"scatter\"}},\"cur_data\":\"60c2c04487e\",\"visdat\":{\"60c2c04487e\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n\nAlgunas preguntas que pueden surgir a partir del gráfico son, por ejemplo:\n\n-   ¿Hay diferencia en el flujo vehicular medio de los días de semana cuando llueve?\n-   ¿Hay diferencia en el flujo vehicular medio de los días de semana cuando llueve?\n-   ¿Hay diferencia en el flujo vehicular medio de los días miércoles respecto de los días viernes?\n\nSiempre, claro, recordando que estamos restringiendo el análisis al flujo vehicular detectado por el radar RD171, en la autopista Lugones, altura Esma.\n\nComo hicimos antes, para lo que sigue, descartamos las observaciones correspondientes a los días 20 y 21 de febrero y 24 de marzo, únicos feriados nacionales del trimestre.\n\n\n\n::: {.cell}\n\n:::\n\n\n\nDel total de días hábiles, entonces, tenemos $19$ observaciones que resultan de días de semana con lluvia, y $43$ observaciones para días de semana sin lluvia.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Días de semana con lluvia: 19 datos\ndatos1 <- flujoclima %>%\n  filter(prcp > 0,\n         tipo_dia == \"Lunes a viernes\")\n\n# Días de semana sin lluvia: 43 datos\ndatos2 <- flujoclima %>%\n  filter(prcp == 0,\n         tipo_dia == \"Lunes a viernes\")\n\nboxplot(\n  datos1$n,\n  datos2$n,\n  col = c(\"firebrick\", \"springgreen4\"),\n  names = c(\"Lluvia\", \"Sin lluvia\")\n)\n```\n\n::: {.cell-output-display}\n![](03_test_hipotesis_files/figure-pdf/unnamed-chunk-17-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\nRealizamos un test t para diferencia de medias.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Test para diferencia de medias\nt.test(\n  x = datos1$n,\n  y = datos2$n,\n  alternative = \"two.sided\",\n  mu = 0,\n  paired = FALSE,\n  conf.level = 0.95\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  datos1$n and datos2$n\nt = 0.3956, df = 29.359, p-value = 0.6953\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -3883.205  5746.884\nsample estimates:\nmean of x mean of y \n 127948.4  127016.6 \n```\n:::\n\n```{.r .cell-code}\ncohen.d(d = datos1$n, f = datos2$n, paired = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCohen's d\n\nd estimate: 0.1173876 (negligible)\n95 percent confidence interval:\n     lower      upper \n-0.4340511  0.6688262 \n```\n:::\n:::\n\n\n\nCon un $p-$valor de $0.6953$, no hay evidencia en la muestra para rechazar la hipótesis de igualdad de flujos medios. Es decir, a partir de la evidencia provista por la muestra, no es posible descartar que el flujo vehicular medio en días sin lluvia difiera del flujo medio cuando llueve.\n\nPodemos hacer otro test para ver si hay diferencia significativa para suponer que el flujo medio de los miércoles difiere del de los lunes. Las observaciones son menos, ya que en el primer trimestre solo se registran $13$ miércoles y $12$ viernes, considerando que se removió el 24 de marzo.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Días de semana con lluvia: 13 datos\ndatos1 <- flujoclima %>%\n  filter(dia == \"miércoles\")\n\n# Días de semana sin lluvia: 13 datos\ndatos2 <- flujoclima %>%\n  filter(dia == \"viernes\")\n\nboxplot(\n  datos1$n,\n  datos2$n,\n  col = c(\"firebrick\", \"springgreen4\"),\n  names = c(\"Miércoles\", \"Viernes\")\n)\n```\n\n::: {.cell-output-display}\n![](03_test_hipotesis_files/figure-pdf/unnamed-chunk-19-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(\n  x = datos1$n,\n  y = datos2$n,\n  alternative = \"two.sided\",\n  mu = 0,\n  paired = FALSE,\n  conf.level = 0.95\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  datos1$n and datos2$n\nt = -0.58982, df = 17.355, p-value = 0.5629\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -9601.871  5401.114\nsample estimates:\nmean of x mean of y \n 127669.5  129769.9 \n```\n:::\n\n```{.r .cell-code}\ncohen.d(d = datos1$n, f = datos2$n, paired = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCohen's d\n\nd estimate: -0.2410676 (small)\n95 percent confidence interval:\n     lower      upper \n-1.0721910  0.5900558 \n```\n:::\n:::\n\n\n\nNuevamente, y con un $p-$valor de $0.5629$, concluimos que no hay evidencia en la muestra para rechazar la hipótesis de igualdad de flujos medios entre esos días, algo que al \"ojo desnudo\" podría parecer significativo. Ocurre, sin embargo, que la variabilidad exhibida en los flujos de los días viernes, parece ser mayor, como se observa en ambos gráficos previos. Una comparación que sí esperaría conducir a un rechazo de la igualdad de flujos medios podría ser la de miércoles y sábados.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Días de semana con lluvia: 13 datos\ndatos1 <- flujoclima %>%\n  filter(dia == \"miércoles\")\n\n# Días de semana sin lluvia: 13 datos\ndatos2 <- flujoclima %>%\n  filter(dia == \"sábado\")\n\nboxplot(\n  datos1$n,\n  datos2$n,\n  col = c(\"firebrick\", \"springgreen4\"),\n  names = c(\"Miércoles\", \"Sábado\")\n)\n```\n\n::: {.cell-output-display}\n![](03_test_hipotesis_files/figure-pdf/unnamed-chunk-21-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(\n  x = datos1$n,\n  y = datos2$n,\n  alternative = \"two.sided\",\n  mu = 0,\n  paired = FALSE,\n  conf.level = 0.95\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  datos1$n and datos2$n\nt = 6.9421, df = 18.759, p-value = 0.000001382\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n 15757.64 29377.77\nsample estimates:\nmean of x mean of y \n 127669.5  105101.8 \n```\n:::\n\n```{.r .cell-code}\ncohen.d(d = datos1$n, f = datos2$n, paired = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCohen's d\n\nd estimate: 2.82569 (large)\n95 percent confidence interval:\n   lower    upper \n1.655577 3.995802 \n```\n:::\n:::\n\n\n\nEl test arroja un $p-$valor prácticamente nulo: podemos concluir que hay evidencia en la muestra para rechazar la hipótesis de igualdad de flujos medios entre los días miércoles y los días sábados. Además, el tamaño del efecto es grande.\n\n------------------------------------------------------------------------\n\n# Acerca de los datos\n\nA continuación, se detallan aspectos de los datasets que conformaron el *dataset* reducido para el desarrollo del ejemplo, a la vez que se incluyen las fuentes de los datos y el código utilizado para pre-procesarlo con la sintaxis de `tidyverse`. De esta forma, puede fácilmente replicarse y/o adaptarse si así se lo desea.\n\nEl dataset reducido con el que se desarrolló el ejemplo y que surge de tal pre-procesamiento, es `flujoclima` de la librería `datosIC`.\n\n## Sobre el *dataset* de clima\n\nLos datos de este ejemplo corresponden a datos de clima del año 2023 tomados de la base de datos meteorológicos y climáticos de MeteoStat [(disponibles acá)](https://meteostat.net/es/station/87582?t=2023-01-01/2023-03-31). En particular, se consideran los datos de la estación meteorológica de Aeroparque (ID 87582) y un conjunto reducido de variables para el período considerado.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclima <-\n  read_csv(\"./fuente/03_test_hipotesis/registro_tiempo_aeroparque_2023.csv\") %>%\n  select(c(1:5, 7:8, 10))\n```\n:::\n\n\n\n## Sobre el *dataset* de flujo vehicular\n\nLos datos de este ejemplo corresponden a datos de flujo vehicular registrado en ciertos radares de AUSA, por hora, en la Ciudad de Buenos Aires para los años 2019 y 2023 [(disponibles acá)](https://data.buenosaires.gob.ar/dataset/flujo-vehicular-por-radares-ausa/resource/c2782157-33be-4119-b8a0-04fdef2668bd).\n\nAlgunas consideraciones, a la fecha, respecto de estos datos:\n\n-   Los *datasets* se encuentran disponibles para los años 2019 a 2023.\n\n-   No todos tienen el mismo formato para el tratamiento de la fecha.\n\n-   Los datos de 2022 no están completos.\n\n-   Los datos de 2023 se encuentran disponibles al primer trimestre.\n\n-   Las coordenadas que georeferencian cada uno de los radares se encuentran \"sucias\" en los datos de 2023. En este capítulo se propuso una posible limpieza.\n\n## *Dataset* pre-procesado: `flujoclima`\n\nPara reducir los datos al estudio de interés, se crea un *dataset* conjunto, `flujoclima`, a partir de los datos de flujo vehicular del primer trimestre de 2023 para el radar RD171 y de clima, en el que se dispone de las siguientes variables.\n\n-   `fecha`: fecha, en el formato mes-día.\n-   `n`: flujo vehicular de la fecha indicada.\n-   `tavg`: temperatura media (°C) registrada en esa fecha.\n-   `prcp`: precipitaciones (mm) registrada en esa fecha.\n-   `dia`: día de la semana de la fecha indicada.\n-   `tipo_dia`: tipo de día (Fin de semana o Lunes a viernes) de la fecha indicada.\n\nEl *dataset* `flujoclima` está disponible en la librería `datosIC`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(datosIC)\nflujoclima\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\nTable: Dataset reducido disponible en la librería 'datosIC'.\n\n|fecha      |      n| tavg| prcp|dia       |tipo_dia        |\n|:----------|------:|----:|----:|:---------|:---------------|\n|2023-01-01 |  74642| 22.8|  0.0|domingo   |Fin de semana   |\n|2023-01-02 | 108794| 22.7|  9.9|lunes     |Lunes a viernes |\n|2023-01-03 | 114959| 25.7|  0.0|martes    |Lunes a viernes |\n|2023-01-04 | 117394| 23.8|  0.0|miércoles |Lunes a viernes |\n|2023-01-05 | 120350| 24.0|  0.0|jueves    |Lunes a viernes |\n|2023-01-06 | 118283| 26.3|  0.0|viernes   |Lunes a viernes |\n|2023-01-07 |  94076| 26.1|  0.0|sábado    |Fin de semana   |\n|2023-01-08 |  92560| 25.7|  0.0|domingo   |Fin de semana   |\n|2023-01-09 | 118142| 25.3|  0.0|lunes     |Lunes a viernes |\n|2023-01-10 | 119916| 25.4|  0.0|martes    |Lunes a viernes |\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR version 4.2.3 (2023-03-15 ucrt)\nPlatform: x86_64-w64-mingw32/x64 (64-bit)\nRunning under: Windows 10 x64 (build 22621)\n\nMatrix products: default\n\nlocale:\n[1] LC_COLLATE=Spanish_Argentina.utf8  LC_CTYPE=Spanish_Argentina.utf8   \n[3] LC_MONETARY=Spanish_Argentina.utf8 LC_NUMERIC=C                      \n[5] LC_TIME=Spanish_Argentina.utf8    \n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] datosIC_0.0.0.9000 devtools_2.4.5     usethis_2.1.6      leaflet_2.1.2     \n [5] ggmap_3.0.2        effsize_0.8.1      vroom_1.6.1        plotly_4.10.1     \n [9] ggfortify_0.4.16   lubridate_1.9.2    forcats_1.0.0      stringr_1.5.0     \n[13] dplyr_1.1.2        purrr_1.0.1        readr_2.1.4        tidyr_1.3.0       \n[17] tibble_3.2.1       tidyverse_2.0.0    ggplot2_3.4.3     \n\nloaded via a namespace (and not attached):\n [1] bitops_1.0-7            fs_1.6.1                bit64_4.0.5            \n [4] RColorBrewer_1.1-3      httr_1.4.5              rprojroot_2.0.3        \n [7] tools_4.2.3             profvis_0.3.7           utf8_1.2.3             \n[10] R6_2.5.1                lazyeval_0.2.2          colorspace_2.1-0       \n[13] urlchecker_1.0.1        withr_2.5.0             sp_1.6-1               \n[16] tidyselect_1.2.0        gridExtra_2.3           prettyunits_1.1.1      \n[19] processx_3.8.0          curl_5.0.0              bit_4.0.5              \n[22] compiler_4.2.3          cli_3.6.1               desc_1.4.2             \n[25] labeling_0.4.2          scales_1.2.1            callr_3.7.3            \n[28] digest_0.6.31           rmarkdown_2.21          jpeg_0.1-10            \n[31] pkgconfig_2.0.3         htmltools_0.5.5         sessioninfo_1.2.2      \n[34] fastmap_1.1.1           htmlwidgets_1.6.2       rlang_1.1.0            \n[37] rstudioapi_0.15.0       shiny_1.7.4             generics_0.1.3         \n[40] farver_2.1.1            jsonlite_1.8.4          crosstalk_1.2.0        \n[43] magrittr_2.0.3          Rcpp_1.0.10             munsell_0.5.0          \n[46] fansi_1.0.4             lifecycle_1.0.3         stringi_1.7.12         \n[49] yaml_2.3.7              pkgbuild_1.4.0          plyr_1.8.8             \n[52] grid_4.2.3              parallel_4.2.3          promises_1.2.0.1       \n[55] crayon_1.5.2            miniUI_0.1.1.1          lattice_0.21-8         \n[58] hms_1.1.3               knitr_1.42              ps_1.7.4               \n[61] pillar_1.9.0            pkgload_1.3.2           glue_1.6.2             \n[64] evaluate_0.20           leaflet.providers_1.9.0 data.table_1.14.8      \n[67] remotes_2.4.2           png_0.1-8               vctrs_0.6.1            \n[70] tzdb_0.3.0              httpuv_1.6.9            RgoogleMaps_1.4.5.3    \n[73] gtable_0.3.4            cachem_1.0.7            xfun_0.39              \n[76] mime_0.12               xtable_1.8-4            later_1.3.0            \n[79] viridisLite_0.4.2       memoise_2.0.1           timechange_0.2.0       \n[82] ellipsis_0.3.2         \n```\n:::\n:::\n\n\n\n# Referencias\n\n-   Datos de flujo vehicular por radares AUSA [(datos disponibles acá)](https://data.buenosaires.gob.ar/dataset/flujo-vehicular-por-radares-ausa/resource/c2782157-33be-4119-b8a0-04fdef2668bd).\n\n-   MeteoStat [(info disponible acá](https://meteostat.net) y [datos disponibles acá)](https://meteostat.net/es/station/87582?t=2022-01-01/2022-12-31).\n\n-   Mapa de CABA [datos disponibles acá](http://cdn.buenosaires.gob.ar/datosabiertos/datasets/barrios/barrios.geojson).\n",
    "supporting": [
      "03_test_hipotesis_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"unnamed-chunk-2\",\"unnamed-chunk-2\",\"unnamed-chunk-2\",\"unnamed-chunk-2\",\"unnamed-chunk-2\",\"unnamed-chunk-2\",\"unnamed-chunk-2\",\"unnamed-chunk-2\",\"unnamed-chunk-2\",\"unnamed-chunk-2\",\"unnamed-chunk-3\",\"unnamed-chunk-3\",\"unnamed-chunk-3\",\"unnamed-chunk-3\",\"unnamed-chunk-3\",\"unnamed-chunk-3\",\"unnamed-chunk-3\",\"unnamed-chunk-3\",\"unnamed-chunk-3\",\"unnamed-chunk-3\",\"unnamed-chunk-6\",\"unnamed-chunk-6\",\"unnamed-chunk-6\",\"unnamed-chunk-6\",\"unnamed-chunk-6\",\"unnamed-chunk-6\",\"unnamed-chunk-6\",\"unnamed-chunk-6\",\"unnamed-chunk-8\",\"unnamed-chunk-8\",\"unnamed-chunk-8\",\"unnamed-chunk-8\",\"unnamed-chunk-8\",\"unnamed-chunk-8\",\"unnamed-chunk-8\",\"unnamed-chunk-8\",\"unnamed-chunk-9\",\"unnamed-chunk-9\",\"unnamed-chunk-9\",\"unnamed-chunk-9\",\"unnamed-chunk-9\",\"unnamed-chunk-9\",\"unnamed-chunk-9\",\"unnamed-chunk-9\",\"unnamed-chunk-10\",\"unnamed-chunk-10\",\"unnamed-chunk-10\",\"unnamed-chunk-10\",\"unnamed-chunk-10\",\"unnamed-chunk-10\",\"unnamed-chunk-10\",\"unnamed-chunk-10\",\"unnamed-chunk-15\",\"unnamed-chunk-15\",\"unnamed-chunk-15\",\"unnamed-chunk-15\",\"unnamed-chunk-15\",\"unnamed-chunk-15\",\"unnamed-chunk-15\",\"unnamed-chunk-15\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.6.2\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"www\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquery\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.12.4\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/jquery\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquery.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.3.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/leaflet\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet.js\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"leafletfix\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.0.0\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/leafletfix\"]}]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leafletfix.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"proj4\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.6.2\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/plugins/Proj4Leaflet\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"proj4.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"Proj4Leaflet\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.0.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/plugins/Proj4Leaflet\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"proj4leaflet.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"rstudio_leaflet\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.3.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/rstudio_leaflet\"]}]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"rstudio_leaflet.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet-binding\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.1.2\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet-providers\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.9.0\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"C:/Users/dpara/AppData/Local/Temp/RtmpG8z4ae\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet-providers_1.9.0.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet-providers-plugin\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.1.2\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/plugins/leaflet-providers-plugin\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet-providers-plugin.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.6.2\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"www\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquery\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.12.4\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/jquery\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquery.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.3.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/leaflet\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet.js\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"leafletfix\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.0.0\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/leafletfix\"]}]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leafletfix.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"proj4\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.6.2\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/plugins/Proj4Leaflet\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"proj4.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"Proj4Leaflet\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.0.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/plugins/Proj4Leaflet\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"proj4leaflet.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"rstudio_leaflet\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.3.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/rstudio_leaflet\"]}]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"rstudio_leaflet.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet-binding\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.1.2\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet-providers\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.9.0\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"C:/Users/dpara/AppData/Local/Temp/RtmpG8z4ae\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet-providers_1.9.0.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet-providers-plugin\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.1.2\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/plugins/leaflet-providers-plugin\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet-providers-plugin.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"leaflet\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.6.2\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"www\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-binding\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"4.10.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"setprototypeof\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/setprototypeof\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"setprototypeof.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"typedarray\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/typedarray\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"typedarray.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquery\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"3.5.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/jquery\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquery.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"crosstalk\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"crosstalk\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.2.0\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"www\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"js/crosstalk.min.js\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"css/crosstalk.min.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"crosstalk\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-htmlwidgets-css\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.11.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/plotlyjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-htmlwidgets.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-main\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.11.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/plotlyjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-latest.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.6.2\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"www\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-binding\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"4.10.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"setprototypeof\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/setprototypeof\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"setprototypeof.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"typedarray\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/typedarray\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"typedarray.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquery\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"3.5.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/jquery\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquery.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"crosstalk\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"crosstalk\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.2.0\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"www\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"js/crosstalk.min.js\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"css/crosstalk.min.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"crosstalk\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-htmlwidgets-css\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.11.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/plotlyjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-htmlwidgets.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-main\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.11.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/plotlyjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-latest.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.6.2\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"www\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-binding\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"4.10.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"setprototypeof\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/setprototypeof\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"setprototypeof.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"typedarray\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/typedarray\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"typedarray.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquery\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"3.5.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/jquery\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquery.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"crosstalk\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"crosstalk\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.2.0\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"www\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"js/crosstalk.min.js\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"css/crosstalk.min.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"crosstalk\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-htmlwidgets-css\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.11.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/plotlyjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-htmlwidgets.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-main\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.11.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/plotlyjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-latest.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.6.2\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"www\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-binding\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"4.10.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"setprototypeof\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/setprototypeof\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"setprototypeof.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"typedarray\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/typedarray\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"typedarray.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquery\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"3.5.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/jquery\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquery.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"crosstalk\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"crosstalk\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.2.0\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"www\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"js/crosstalk.min.js\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"css/crosstalk.min.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"crosstalk\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-htmlwidgets-css\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.11.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/plotlyjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-htmlwidgets.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-main\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.11.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/plotlyjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-latest.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.6.2\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"www\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-binding\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"4.10.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"setprototypeof\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/setprototypeof\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"setprototypeof.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"typedarray\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/typedarray\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"typedarray.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquery\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"3.5.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/jquery\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquery.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"crosstalk\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"crosstalk\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.2.0\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"www\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"js/crosstalk.min.js\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"css/crosstalk.min.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"crosstalk\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-htmlwidgets-css\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.11.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/plotlyjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-htmlwidgets.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-main\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.11.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"htmlwidgets/lib/plotlyjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly-latest.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"plotly\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}